### ISSUE TITLE
Question 4 Conditions are unclear?

### ISSUE THREAD

**Issue by saltedseacorn** [Code-the-Dream-School/web-basics-2-week-2#1]
Question 4 is as follows: 
```
//------------------------ Question 4 ---------------------------
// In the function below we are giving you an array of objects, 
// each one with the same properties.
// Ask to the user for 3 different options to sorting the array
// from the highest to lowest.
// In the case of a string, the criteria to sort must be the length
// of the string.
// The first one is sorting the array of objects based on the title property.
// The second one sorting the array of objects based on the author property,
// the third one based on the library property. finally, the return value has to be the string
// sorted of the property selected separeted with a semicolon. Remember
// you have to sort all of the array based on the selected property
// example:
// if the user select sorting by title the return value must 
// be: "Mockingjay: The Final Book of The Hunger Games; Walter Isaacson;
// The Road Ahead"
```
This is my understanding of the criteria so far:

* In the function below you are given an array of objects. Note that each object inside the array holds the same key values.
* You are to ask the user to select from three options.
     1. If the user requests to arrange by title, return a sorted string based on the title length from longest to shortest.
     2. If the user requests to arrange by author, return a sorted string based on the author name from longest to shortest. 
     3. If the user requests to arrange by library identification number, return a sorted string based on highest number to 
         shortest.
* Note that when returning your string to the user, the format should include:
```
"; "
```
between each returned property. For example, if the user were to request to sort the library object by title, the returned result should be:
```
 "Mockingjay: The Final Book of The Hunger Games; Walter Isaacson; The Road Ahead"
```

If this is correct, could someone please clarify? Thank you so much for your time.

**Comment by saltedseacorn** [comment]
Got word that we are closer to what we are looking for! Closing issue. Thank you all again.

**Comment by mamooredesigns** [comment]
Changes made, pull request submitted for approval.
